# welcome to RsCSS
# This is where CSS will be stored for yew.rs

# example usage


[example_div]
# 'top level' properties can be simply defined by their names
color = "white"


# objects with several properties can be defined in a group
box={shadow="0.5px", sizing="0.5%"}

# or as dotted
border.style="solid"
border.left={color="blue", width="2px"}
border.right={color="red", width="4px"}

# for features with multiple options, 'self' can be used as a one liner
background={self="scroll"} 

